### ISSUE TITLE
Exception when trying to use DbLocalizationProvider in test server

### ISSUE THREAD

**Issue by hiepto** [valdisiljuconoks/LocalizationProvider#41] opened 2016-09-05 07:27 UTC
[InvalidOperationException: Collection was modified; enumeration operation may not execute.]
System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource) +56
System.Collections.Generic.Enumerator.MoveNextRare() +13711134
EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture) +149
EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, String& localizedString) +88
EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String resourceKey, CultureInfo culture, String& localizedString) +103
CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.DisplayResolutionBase.Translate(String resurceKey) +114
CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.DisplayResolutionBase..ctor(String name, Int32 width, Int32 height) +64
lambda_method(Closure , IBuildSession , IContext ) +179

[StructureMapBuildException: Error while building type CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.AndroidVerticalResolution. See the inner exception for details
1.) new AndroidVerticalResolution()
2.) CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.AndroidVerticalResolution
3.) Instance of CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.AndroidVerticalResolution
4.) Container.GetInstance(CustomCore.Framework.EPi.UI.Core.Rendering.Resolutions.AndroidVerticalResolution)
]
lambda_method(Closure , IBuildSession , IContext ) +1033
StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context) +130
StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle) +203
StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph) +171
StructureMap.Container.GetInstance(Type pluginType) +351
EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) +55

[ActivationException: Activation error occurred while trying to get instance of type AndroidVerticalResolution, key ""]
EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) +156
EPiServer.Initialization.Internal.CmsCoreInitialization.InitializeDisplayOptionsAndResolutions(InitializationEngine context) +751
EPiServer.Initialization.Internal.CmsCoreInitialization.Initialize(InitializationEngine context) +52
EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key) +56
EPiServer.Framework.Initialization.InitializationEngine.InitializeModules() +348

[InitializationException: Initialize action failed for Initialize on class EPiServer.Initialization.Internal.CmsCoreInitialization, EPiServer, Version=9.12.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7]
EPiServer.Framework.Initialization.InitializationEngine.InitializeModules() +886
EPiServer.Framework.Initialization.InitializationEngine.ExecuteTransition(Boolean continueTransitions) +153
EPiServer.Framework.Initialization.InitializationModule.EngineExecute(HostType hostType, Action`1 engineAction) +786
EPiServer.Framework.Initialization.InitializationModule.FrameworkInitialization(HostType hostType) +190
EPiServer.Global..ctor() +84
ASP.global_asax..ctor() +9

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +138
System.Activator.CreateInstance(Type type, Boolean nonPublic) +105
System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark) +1481
System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) +191
System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) +27
System.Web.HttpRuntime.CreateNonPublicInstance(Type type, Object[] args) +82
System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +300
System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by valdisiljuconoks** [comment] 2016-09-05 14:12
Unfortunately, on eempty proejct or AlloyTech sample site., I'm not able to reproduce this issue.

Following packages were used:

```
<package id="DbLocalizationProvider.EPiServer" version="2.0.1" targetFramework="net46" />
<package id="EPiServer.CMS" version="9.12.2" targetFramework="net46" />
<package id="EPiServer.CMS.Core" version="9.12.2" targetFramework="net46" />
<package id="EPiServer.CMS.UI" version="9.9.1" targetFramework="net46" />
<package id="EPiServer.CMS.UI.Core" version="9.9.1" targetFramework="net46" />
<package id="EPiServer.Framework" version="9.12.2" targetFramework="net46" />
<package id="EPiServer.Logging.Log4Net" version="2.0.0" targetFramework="net452" />
<package id="EPiServer.Packaging" version="3.2.4" targetFramework="net46" />
<package id="EPiServer.Packaging.UI" version="3.2.4" targetFramework="net46" />
<package id="LocalizationProvider" version="2.0.4" targetFramework="net46" />
```

Few questions:
1) Does the problem occur only in test env.? or also in local dev?
2) Does it happen always?
3) When removed DbLocalizationProvider package - problem solved?

Repro project would be ideal...

**Comment by hiepto** [comment] 2016-09-05 14:27
Hi Valdis,
Please find my answer below:
1) Does the problem occur only in test env.? or also in local dev?
It only happen on test env which is one core virtual machine. 
It works fine on local dev ( Quadcore )

2) Does it happen always?
Yes, it always happens
.
3) When removed DbLocalizationProvider package - problem solved?
Yes, when we removed DbLocalizationProvider, it worked as normal

Will try to send you project to reproduce.

**Comment by valdisiljuconoks** [comment] 2016-09-07 19:47
Hi,

Any news of getting hands on repo project?
I'm trying to bang my head against the wall and come up with scenario where access to .Providers might happen.. Which the root cause of the exception.

Meanwhile, I guess if you can modify base resolution class, try add this around:
```
private string Translate(string resurceKey)
{
    string value;

    try
    {
        if(!LocalizationService.Service.TryGetString(resurceKey, out value))
        {
            value = resurceKey;
        }
    }
    catch (Exception)
    {
        value = resurceKey;
    }

    return value;
}
```

**Comment by andrewmarkham** [comment] 2016-09-15 14:43
Hi I have been having the same issue and managed to resolve this with a change to DisplayResolutionBase class.

See the blog post 'http://world.episerver.com/forum/developer-forum/EPiServer-7-CMS/Thread-Container/2013/2/Translating-Names-in-IDisplayResolution/' for the changes.

But once we had this fix in place we experience another error.

```
2016-09-15 14:35:03,254 [1] ERROR EPiServer.Framework.Initialization.InitializationEngine: Initialize action failed for 'Initialize on class EPiServer.Initialization.Internal.XFormsInitialization, EPiServer, Version=9.12.0.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetString(String resourceKey)
   at EPiServer.Initialization.Internal.XFormsInitialization.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass3_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at EPiServer.Framework.Localization.ProviderBasedLocalizationService.LoadString(String[] normalizedKey, String originalKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.TryGetStringByCulture(String originalKey, String[] normalizedKey, CultureInfo culture, String& localizedString)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, FallbackBehaviors fallbackBehavior, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetStringByCulture(String resourceKey, CultureInfo culture)
   at EPiServer.Framework.Localization.LocalizationService.GetString(String resourceKey)
   at EPiServer.Initialization.Internal.XFormsInitialization.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.<>c__DisplayClass3_0.<Initialize>b__0()
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Execute(Action a, String key)
   at EPiServer.Framework.Initialization.Internal.ModuleNode.Initialize(InitializationEngine context)
   at EPiServer.Framework.Initialization.InitializationEngine.InitializeModules()
```
As you can see from the log above the underlying error is the same 

> System.InvalidOperationException: Collection was modified; enumeration operation may not execute

I am wondering if this is caused by the latest version of EPiServer?

Thanks

**Comment by valdisiljuconoks** [comment] 2016-09-15 18:29
Andrew, which version of EPi are you running? Your server is also single core?

**Comment by valdisiljuconoks** [comment] 2016-09-15 18:30
What you leave all the dlls in place, but comment out database driven localization provider in EpiserverFramework.config file?

**Comment by andrewmarkham** [comment] 2016-09-16 08:53
Hi Valdis,  The packages.config is below

```
<packages>
  <package id="BVN.404Handler" version="4.1.1" targetFramework="net461" />
  <package id="Castle.Core" version="3.3.3" targetFramework="net461" />
  <package id="Castle.Windsor" version="3.3.0" targetFramework="net461" />
  <package id="DbLocalizationProvider.AdminUI.EPiServer" version="2.0.1" targetFramework="net461" />
  <package id="DbLocalizationProvider.EPiServer" version="2.0.1" targetFramework="net461" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
  <package id="EPiServer.AddOns.Helpers" version="0.1.0.0" targetFramework="net461" />
  <package id="EPiServer.CMS" version="9.12.0" targetFramework="net461" />
  <package id="EPiServer.CMS.Core" version="9.12.0" targetFramework="net461" />
  <package id="EPiServer.CMS.UI" version="9.8.2" targetFramework="net461" />
  <package id="EPiServer.CMS.UI.Core" version="9.8.2" targetFramework="net461" />
  <package id="EPiServer.ContentCollaboration" version="1.2.0.9000" targetFramework="net461" />
  <package id="EPiServer.Forms" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Forms.Core" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Forms.UI" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Framework" version="9.12.0" targetFramework="net461" />
  <package id="EPiServer.GoogleAnalytics" version="1.9.3.9000" targetFramework="net461" />
  <package id="EPiServer.Logging.Log4Net" version="2.0.0" targetFramework="net461" />
  <package id="EPiServer.Packaging" version="3.2.4" targetFramework="net461" />
  <package id="EPiServer.Packaging.UI" version="3.2.4" targetFramework="net461" />
  <package id="EPiServer.VisitorGroupsCriteriaPack" version="1.2.0.9000" targetFramework="net461" />
  <package id="Geta.SEO.Sitemaps" version="1.5.7" targetFramework="net461" />
  <package id="LocalizationProvider" version="2.0.0" targetFramework="net461" />
  <package id="log4net" version="2.0.5" targetFramework="net461" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.Providers.Core" version="2.0.0" targetFramework="net461" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net461" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net461" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net461" />
  <package id="Newtonsoft.Json" version="8.0.3" targetFramework="net461" />
  <package id="NuGet.Core" version="2.5.0" targetFramework="net461" />
  <package id="OctoPack" version="3.0.71" targetFramework="net461" developmentDependency="true" />
  <package id="Owin" version="1.0" targetFramework="net461" />
  <package id="POSSIBLE.RobotsTxtHandler" version="2.0.2.0" targetFramework="net461" />
  <package id="SlowCheetah" version="2.5.15" targetFramework="net461" />
  <package id="structuremap.web-signed" version="3.1.6.191" targetFramework="net461" />
  <package id="structuremap-signed" version="3.1.6.191" targetFramework="net461" />
</packages>
```

The server we are deploying to is an AWS t2-small.  This is a single core machine.

We are also using the same version of the package with a different version of EPiServer and we have not experienced these issues.  The details are below.

```
  <package id="DbLocalizationProvider" version="1.3.3" targetFramework="net461" />
  <package id="DbLocalizationProvider.AdminUI" version="1.3.1" targetFramework="net461" />
  <package id="DbLocalizationProvider.AdminUI.EPiServer" version="2.0.1" targetFramework="net461" />
  <package id="DbLocalizationProvider.EPiServer" version="2.0.1" targetFramework="net461" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net461" />
  <package id="EPiServer.AddOns.Helpers" version="0.1.0.0" targetFramework="net461" />
  <package id="EPiServer.CMS" version="9.10.0" targetFramework="net461" />
  <package id="EPiServer.CMS.Core" version="9.10.0" targetFramework="net461" />
  <package id="EPiServer.CMS.UI" version="9.6.2" targetFramework="net461" />
  <package id="EPiServer.CMS.UI.Core" version="9.6.2" targetFramework="net461" />
  <package id="EPiServer.Forms" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Forms.Core" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Forms.UI" version="3.0.0.0" targetFramework="net461" />
  <package id="EPiServer.Framework" version="9.10.0" targetFramework="net461" />
  <package id="EPiServer.GoogleAnalytics" version="1.9.3.9000" targetFramework="net461" />
  <package id="EPiServer.Logging.Log4Net" version="2.0.0" targetFramework="net461" />
  <package id="EPiServer.Packaging" version="3.2.4" targetFramework="net461" />
  <package id="EPiServer.Packaging.UI" version="3.2.4" targetFramework="net461" />
  <package id="EPiServer.Search" version="8.0.0" targetFramework="net461" />
  <package id="EPiServer.VisitorGroupsCriteriaPack" version="1.2.0.9000" targetFramework="net461" />
```

**Comment by andrewmarkham** [comment] 2016-09-16 08:54
> What you leave all the dlls in place, but comment out database driven localization provider in EpiserverFramework.config file?

When we comment this out the issue goes away.

**Comment by hiepto** [comment] 2016-09-16 08:58
Hi Valdis,
It seems the error happens when the server is single core server. 
And when we have duplicate resource key accross the solution.

**Comment by valdisiljuconoks** [comment] 2016-09-16 08:59
So your observation is that it blows up with particular episerver version?

**Comment by valdisiljuconoks** [comment] 2016-09-16 09:00
Hiep, double resource keys = you have multiple localization providers that holds the same key?

**Comment by hiepto** [comment] 2016-09-16 09:05
For example: you put [ResourceKey("pagetitle")] in several places in the project. 
Strange thing is it works fine on multiple core machine.

**Comment by valdisiljuconoks** [comment] 2016-09-16 09:20
alright, at least some clue..

**Comment by andrewmarkham** [comment] 2016-09-16 09:33
Hi Valdis,

> So your observation is that it blows up with particular episerver version?

Yep, I do feel that this is the case.

Thanks

**Comment by andrewmarkham** [comment] 2016-09-16 10:59
Hi Valdis,

Just to update you.  The team working with the older version of EPiServer are actually experiencing this issue, but in their case it is intermittent.

They are also getting the error within the development environment, and the machine are multi-core.

I will try and get a demo site created this weekend to demo the issue.

Thanks

**Comment by valdisiljuconoks** [comment] 2016-09-16 11:06
that would be awesome!

**Comment by valdisiljuconoks** [comment] 2016-09-16 12:34
Hiep, I was able to launch project with duplicate keys. Last wins.
Ahh, this is weird.. Just spinned up machine with single core - no issues.

**Comment by valdisiljuconoks** [comment] 2016-09-16 14:14
Hiep, Andrew, 

I'm now speculating as I can't really repo the issue here locally.
Just thought. If you can download the source and build it up use dll from the build and drop it in your project..

Try to uncomment following filter statement and see - can you repo the issue.

https://github.com/valdisiljuconoks/LocalizationProvider/blob/master/DbLocalizationProvider/Queries/GetAllTranslations.cs#L28

**Comment by valdisiljuconoks** [comment] 2016-09-20 14:52
Guys, any follow-ups on this?

**Comment by valdisiljuconoks** [comment] 2016-09-20 14:53
Not to allow duplicates - I created new issue #42

**Comment by andrewmarkham** [comment] 2016-09-20 18:49
Hi,

I spent some time over the weekend trying to recreate the issue, and didn't have much luck.  I will keep on trying.

Thanks

**Comment by valdisiljuconoks** [comment] 2016-09-21 08:01
Even more weird :)

**Comment by andrewmarkham** [comment] 2016-09-21 08:27
I created a new azure instance last night with a single core.  Still not problem.

Both the issues are happening in the initialization process where the failing module is trying to use the EPiServer translation features.  Could this be where the issues is, and is in fact some form of data issue?

Thanks

**Comment by valdisiljuconoks** [comment] 2016-09-21 09:48
One of the potential cause could that there is method in provider `GetAllStrings` that originally was using `StartWith` to return resources. Might be so that actually database localization returns only subset of available resources and not all of them. I'm not sure whether this is the root cause.

However, original exception is thrown in `foreach` where EPiServer is iterating over localization `Providers` collection and asking for resources from underlying providers. If collection changes (which might be - because there are code fragments that are adding providers directly to the collection) then mentioned exception above is thrown. 

The sad part is - there is no clear repo..

**Comment by valdisiljuconoks** [comment] 2017-02-17 11:46
Thanks to @bmcdavid, for finding temporary fix for this issue.

https://gist.github.com/bmcdavid/79caec34d36a0d763df2b3e69d9a2a85

If you experience this bug, please try Brad's solution. I'm not confident yet to override localization provider in the package.. Needs more research..

**Comment by bmcdavid** [comment] 2017-02-17 15:02
I am also trying to see if Episerver will address the issue in the ProviderBasedLocalizationService.LoadString method. I will update here when they let me know.

**Comment by bmcdavid** [comment] 2017-02-28 21:17
A bug has been opened with Episerver. There currently is no resolution date, so please use my workaround until the bug is fixed by the product team.

http://world.episerver.com/support/Bug-list/bug/CMS-6572

**Comment by valdisiljuconoks** [comment] 2017-06-05 19:07
Officially EPiServer fixed this in 10.7 version. However, looking at source of 10.9, see still:

```
LoadString(...)
{
    foreach (LocalizationProvider provider in this.Providers)
...
```

I can still reproduce it in 10.9.

CC: @egandalf, @bmcdavid, @davidknipe

**Comment by valdisiljuconoks** [comment] 2017-08-15 10:18
Notified EPiServer that bug is not entirely fixed.

**Comment by valdisiljuconoks** [comment] 2017-12-29 09:01
The issue still open in CMS 11. This is an update for @bmcdavid code: https://gist.github.com/valdisiljuconoks/ebcd8db758801698bfe14a298cdf5cf6

**Comment by valdisiljuconoks** [comment] 2017-12-29 09:03
hm.. interesting. while migrating to CMS 11 - get the same error. but now looking into Epi source code - I see that there is a fix using provider list snapshots. Need to test more....

**Comment by valdisiljuconoks** [comment] 2017-12-29 22:20
Looks like fix is not needed anymore. Episerver has fixed provider enumeration issue. Thx everyone.

cc: @bmcdavid

**Closed by valdisiljuconoks** 2017-12-29 22:20 UTC
Labels: bug

**Comment by aperisic** [comment] 2018-03-13 13:23
Just so you would know when you bump on this issue
https://world.episerver.com/support/Bug-list/bug/CMS-7749
